apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apache2-pvc
spec:
  resources:
    requests:
      storage: 10Mi
  #volumeMode: Filesystem
  storageClassName: apache2
  accessModes:
    - ReadWriteMany
