apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  serviceName: svc
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
          name: mariadb
        volumeMounts:
          - name: db
            mountPath: /var/lib/mysql
        env:
        - name: MARIADB_ALLOW_EMPTY_ROOT_PASSWORD
          valueFrom:
            secretKeyRef: 
              key: mariadb-allow-empty-root-password
              name: mariadb-secret
        - name: MARIADB_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef:
              key: mariadb-root-user-password
              name: mariadb-secret
      volumes:
      - name: db
        persistentVolumeClaim:
          claimName: mariadb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-svc
spec:
  selector:
    app: mariadb
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
