apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
spec:
  resources:
    requests:
      storage: 10Mi
  #volumeMode: Filesystem
  storageClassName: mariadb
  accessModes:
    - ReadWriteMany
