serviceMonitor:
  enabled: true
  additionalLabels:
    release: prometheus
mysql:
  db: ""
  host: "mariadb-svc"
  # config my.cnf https://dev.mysql.com/doc/c-api/8.0/en/mysql-options.html
  additionalConfig:
    # - connect-timeout=5
    # - debug
  pass: "password"
  port: 3306
  protocol: ""
  user: "exporter"
